### ISSUE TITLE
Baidu wrong

### ISSUE THREAD

**Issue by lisinaner** [NikolaiT/se-scraper#11]
Hello, Baidu is really used. There are a lot of problems in it, it doesn't support multiple pages, and multiple search words will cause duplication. I guess it is not cleaned before typing.

**Comment by lisinaner** [comment]
If you use the first version of the Baidu module, there are fewer bugs. If the first search term contains the content of the second search term, the result will be the first one. It may trigger the smart prompt.

**Comment by NikolaiT** [comment]
fill fix soon. thanks for the issue.
