### ISSUE TITLE
run multiple search engines and execute all promises  before other action

### ISSUE THREAD

**Issue by kederrac** [NikolaiT/se-scraper#12]
I was trying to use express with se-scraper and  have multiple search engines. It works fine but it just run only the last search engine. (for exemple for ['bing', 'google', 'webcrawler'] it will return 3 time the results of   'webcrawler').

The issue seems to be solved after a bit of debug, at line 43 in node_scraper.js I just change "config = event" with "let config = event"

**Comment by NikolaiT** [comment]
> The issue seems to be solved after a bit of debug, at line 43 in node_scraper.js I just change "config = event" with "let config = event"

I did this and uploaded the changes. Did it resolve your issue?

**Comment by kederrac** [comment]
yep, it resolve my issue, thx!
