### ISSUE TITLE
Missing submodule files and package.json missing some dependencies

### ISSUE THREAD

**Issue by HugoPoi** [NikolaiT/se-scraper#14]
I currently try to setup a development environment and I think there is some uncommitted files because there is no `.gitmodules`.

And `puppeteer-cluster` is not the original version ?

Me and my team will really want to contribute to this project.

**Comment by NikolaiT** [comment]
No `puppeteer-cluster` is not the original version, because the original version doesn't support passing chrome arguments to the launch of new browsers ( which I need in order to set a new proxy per browser)

See this issue I made in their repo: https://github.com/thomasdondorf/puppeteer-cluster/issues/107

I am not quite comfortable using puppeteer cluster, because the author doesn't know when he will make major changes to their API. 

But I honestly don't know what would be a good solution to parallelize scraping. Using one proxy per tab is not possible by chrome design. The only way right now is to use one proxy per browser. And this Is what I do.

How can I help that you can start contributing?

**Comment by HugoPoi** [comment]
You reference `puppeteer-cluster` in https://github.com/NikolaiT/se-scraper/tree/master/src but there is no `.gitmodules` for indicate where is your fork of `puppeteer-cluster` (maybe you just haven't publish it) ? I can setup the `.gitmodule` with the provided patch in https://github.com/thomasdondorf/puppeteer-cluster/issues/107

**Comment by NikolaiT** [comment]
I honestly never used a submodule. 

I assume I need to set it up as described [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules) ?

But how can I set up a submodule by keeping the changes I did to puppeteer-cluster? Probably I need to do it all again right?

**Comment by HugoPoi** [comment]
A submodule in git is just a link to another repository and reference a specific commit. But not very obvious to use.
1. First you need to publish your change of `puppeter-cluster`
Assuming you just clone it from the original repository in your current source folder (this is bad), you need to click fork button on https://github.com/thomasdondorf/puppeteer-cluster and in your source folder you need to change the remote url to the new one (the fork) `git remote set-url origin https://github.com/NikolaiT/puppeter-cluster.git` be sure to be in `src/puppeter-cluster`. Then you can push your change of puppeteer-cluster with git push command.
2. Second you need to properly add src/puppeter-cluster as a module in this repository.
 `git submodule add ./src/puppeter-cluster` this will generate a `.gitmodules` file but with wrong url you need to edit manually and change `url = ./src/puppeter-cluster` to `url = https://github.com/NikolaiT/puppeter-cluster` then commit the `.gitmodules` file and push it here.

**Comment by NikolaiT** [comment]
Many thanks for the very good description.

I fixed it, now using proper submodule and I forked it from puppeteer-cluster.

There is a `gitmodules` file:

```
nikolai@nikolai:~/se-scraper$ cat .gitmodules 
[submodule "src/puppeteer-cluster"]
	path = src/puppeteer-cluster
	url = https://github.com/NikolaiT/puppeteer-cluster
```

**Comment by HugoPoi** [comment]
Good, looking great now.
For test and build se-scraper :
```
git clone --recurse-submodules git@github.com:NikolaiT/se-scraper.git
cd se-scraper/src/puppeteer-cluster
npm install
npm build
cd ../..
npm install
npm run test
```
We may add this in a CONTRIBUTING.md.
It's not perfect, in this particular case it make more sense to maybe publish the modified version of puppeteer-cluster in npm and add-it as a dependence. Or maybe add as git dependence in package.json with postinstall-script for building puppeteer-cluster.
