### ISSUE TITLE
Unable to use with authenticated proxy

### ISSUE THREAD

**Issue by NSpehler** [NikolaiT/se-scraper#18]
Hello there,

I'm trying to make my requests using an authenticated proxy but I'm unable to make it work.

The formats that I've tried:
```
http://username:password@ip:port
http://ip:port:username:password
username:password@ip:port
ip:port:username:password
```

Here's the output that I'm getting (regardless of the format used):
```
my_server_ip vs http://username:password@ip:port
Proxy not working properly.
Failed to load the search engine: load_search_engine()
```

Any ideas on how I can use an authenticated proxy with se-scraper?

Thanks,
Nicolas

**Comment by NikolaiT** [comment]
will fix this tomorrow

**Comment by obiwankenoobi** [comment]
any update on that? I tried to set prop `proxy` in the config object and I am getting the same result

**Comment by NikolaiT** [comment]
It seems this is currently not possible to use socks5 proxy auth with chromium. Here is a [detailed explanation](https://blog.apify.com/how-to-make-headless-chrome-and-puppeteer-use-a-proxy-server-with-authentication-249a21a79212).

As  a workaround you can use a local forwarding proxy, or you can just use a proxy server without authentication (and authenticated by IP filtering as I am doing it).

This is how you pass the flag:

```javascript

const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        args: [
            // SET PROXY HERE
            '--proxy-server=socks5://IP:PORT',
            '--disable-infobars',
            '--window-position=0,0',
            '--ignore-certifcate-errors',
            '--ignore-certifcate-errors-spki-list',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--disable-gpu',
            '--window-size=1920x1080',
            '--hide-scrollbars',
            '--disable-notifications',
            '--no-sandbox',
            '--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/71.0.3578.98 Chrome/71.0.3578.98 Safari/537.36'
        ],
        headless: true
    });
    var page = await browser.newPage();
    await page.setViewport({width: 1920, height: 926});
    await page.goto('http://ipinfo.io/json');
    console.log(await page.content());
    await browser.close();
})();

```

**Comment by hybmg57** [comment]
@NikolaiT are you able to help us how to set up local proxy? I have auth based proxy that I need to use but having trouble setting it up
