### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by slotix** [NikolaiT/se-scraper#20]
Awsome module!
Do you plan to build "se-scraper" docker image?
Thank you.

**Comment by NikolaiT** [comment]
I dont have much experience with Docker, but I will look into it very soon and add such a Docker Image.

**Comment by slotix** [comment]
I'm going to add docker image myself and share with the community.

**Comment by pelatimtt** [comment]
I'm getting this error while trying to launch se_scraper in docker

```
UnhandledPromiseRejectionWarning: Error: Unable to launch browser for worker, error message: Failed to launch chrome!
[0514/035629.769555:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

Are you facing the same issue ?

**Comment by kederrac** [comment]
use this config 
` let config = {
            random_user_agent: true,
            write_meta_data: true,
            sleep_range: "",
            chrome_flags:[ ],
            search_engine: searchEngine,
            debug: false,
            verbose: false,
            // the list of keywords to scrape
            keywords: keys,
            num_pages: num_pages,
            // whether to start the browser in headless mode
            headless: true,
//            output_file: `${searchEngine}.json`
            puppeteer_cluster_config:{
                    timeout:600000,
                    monitor:false,
                    concurrency:1,
                    maxConcurrency:1
                }
        };`

**Comment by slotix** [comment]
> I'm getting this error while trying to launch se_scraper in docker
> ...
> 
> Are you facing the same issue ?

I have no such issue.  
Did you try to follow the steps described at https://github.com/NikolaiT/se-scraper/pull/21 ?

**Comment by slotix** [comment]
Try to add "--no-sandbox"  parameter to "chrome_flags"

```
curl -XPOST http://0.0.0.0:3000 -H 'Content-Type: application/json' \
-d '{
    "user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36",
    "random_user_agent":true,
    "sleep_range":"",
"search_engine":"baidu",
    "debug":true,
    "verbose":true,
    "keywords":[ "cat",  "mouse" ],
    "keyword_file":"",
    "num_pages":1,
    "headless":true,
    "chrome_flags":["--no-sandbox" ],
    "output_file":"examples/results/baidu.json",
    "block_assets":false,
    "custom_func":"",
    "proxy":"",
    "proxy_file":"",
    "test_evasion":false,
    "apply_evasion_techniques":true,
    "log_ip_address":false,
    "log_http_headers":false,
    "puppeteer_cluster_config":{
        "timeout":600000,
        "monitor":false,
        "concurrency":1,
        "maxConcurrency":1
    }
}'
```

**Comment by Axel-G** [comment]
i take the image from docker-hub. the port of docker image (on localhost ip same as the direct container ip) is closed. with nmap scan same result.

**Comment by slotix** [comment]
pull the latest version from docker hub 
run `docker run -it -e HOST=0.0.0.0 -e PORT=3000 -p 3000:3000  slotix/se-scraper
`
try another port instead of 3000

**Comment by Axel-G** [comment]
thx @slotix  for the fast help. new image runs and i get a request.
if the env's HOST and PORT necassary, you should edit the pull request.

thx a lot

**Comment by slotix** [comment]
@Axel-G updated pull request

**Comment by tobiasmuehl** [comment]
Can we close this?
