### ISSUE TITLE
Regex for keywords?

### ISSUE THREAD

**Issue by SimonSays909** [NikolaiT/se-scraper#24]
Hi,

First of all - great scraper! really, truly, awesome work! It's a joy playing around with this!

So, my question is in regard to the use of regex for keywords. I wanted to use regex for specialized search string patterns, but I can't figure out how to get this to work. If I wanted all keywords that had 0-5 characters (a-z, 0-9) and ended with the characters 'ej6', how would I make that work?

I attempted:
```
let config = {
    keywords: ['/^[a-z0-9]{0,5}$/ej6'],
```

```
let config = {
    keywords: ['/^[a-z0-9]{0,5}$/' + 'ej6'],
```
... along with a few other attempts, but I honestly have no idea how to make it work with regex, and maybe there is an even better way using JS (?).

Best,
Simon

**Comment by NikolaiT** [comment]
Do you want to search all possible words with the pattern `/[a-z0-9]{0,5}ej6/` ?

Then just generate them via script.

For example in python:

```python
import string
import itertools

keywords = list(itertools.combinations(string.ascii_lowercase + string.digits, 5))

with open('keywords.txt', 'w') as f:
    for kw in keywords:
        f.write(''.join(kw)+'ej6\n')
```
