### ISSUE TITLE
custom results selector

### ISSUE THREAD

**Issue by ayhid** [NikolaiT/se-scraper#28]
With the python version I recall being able to get google ads with the search results.
But with this version and after looking at the google results selectors I can tell that it is not possible.

Is there a way to give the developer the ability to provide a custom selector ?

**Comment by NikolaiT** [comment]
The problem is what exactly should I do with a custom selector?
get the innerHtml of the targeted nodes? The innerText? Only the first result? 

Usually a selector is not enough, we need some parsing logic. 

Do you want me to add the something like the following?
```
config = {
...
   custom_selector_google: {
      '.main .someElements': { // this is the main selector that grabs a bunch of container classes where the interesting elements are located
         'name': '.name h2', // this pulls out the data we are interested in
         'price': 'span.price p',
         ....
     }
   }
```

Regards

**Comment by ayhid** [comment]
You' are right it's complicated to provide a generic solution with just a selector.
May be adding a kind of callback function with the the cheerio results so we can override the results object from the outside.

What do you think ?

**Comment by NikolaiT** [comment]
I have added the capability to pass custom scraper classes to se-scraper. See here: https://github.com/NikolaiT/se-scraper/blob/master/examples/custom_scraper.js

This way you can copy the existing google scraper class and define *all* your own behavior you want, including parsing ads.

**Comment by ayhid** [comment]
That's perfect thanks a lot for the tip.
