### ISSUE TITLE
Modularize scraper modules

### ISSUE THREAD

**Issue by tobiasmuehl** [NikolaiT/se-scraper#30]
We don't need this but I think it's a cool idea.

https://github.com/NikolaiT/se-scraper/blob/06d500f75c0dd38e9cabb36b041121852034db93/src/node_scraper.js#L35-L55

Instead of hardcoding the list of possible search engines, allow use of any class that extends the base class. Can be a polymorphic addition of the current codebase.

https://github.com/NikolaiT/se-scraper/blob/06d500f75c0dd38e9cabb36b041121852034db93/src/node_scraper.js#L353-L357

```js
let obj;
if (typeof this.config.search_engine === 'string') {
  obj = getScraper(this.config.search_engine, { 
     config: this.config, 
     context: {}, 
     pluggable: this.pluggable, 
 });
} else {
  obj = new this.config.search_engine({
    config: this.config,
    context: {},
    pluggable: this.pluggable
  })
}

```

Then it's possible for the community to write own scraper modules
```js
const se_scraper = require('se-scraper');
const thirdPartyScraper = require('se-scraper-third-party')

(async () => {
    let scrape_job = {
        search_engine: thirdPartyScraper,
        keywords: ['lets go boys'],
        num_pages: 1,
    };

    var results = await se_scraper.scrape({}, scrape_job);

    console.dir(results, {depth: null, colors: true});
})();
```

**Comment by NikolaiT** [comment]
Very good idea. Will implement tomorrow.

Often the maintenance of existing scrapers is tiresome because the html of search engines changes every now and then. This will give users the possibility to derive their own parsing logic.

**Comment by NikolaiT** [comment]
Custom scrapers now implemented. 

See an [example for reference](https://github.com/NikolaiT/se-scraper/blob/master/examples/custom_scraper.js)
