### ISSUE TITLE
incomplete dataset is returned if puppeteer_cluster_config -> maxConcurrency > 1 

### ISSUE THREAD

**Issue by slotix** [NikolaiT/se-scraper#37]
examples/multiple_browsers.js 

from the list of keywords ['news', 'mountain', 'what', 'are good', 'keyword', 'who', 'nice']
Not all results are returned in case of maxConcurrency is not equal to 1.

Everything is good if 
```
puppeteer_cluster_config: {
maxConcurrency: 1,
}
```

**Comment by NikolaiT** [comment]
I am really sorry.

I included a pull request with completely wrong logic a couple of weeks ago. Now it works as expected again.

**Comment by GeorgeWillaman** [comment]
Filed another issue.
I think it might be broke again
