### ISSUE TITLE
... detected the scraping. Aborting.

### ISSUE THREAD

**Issue by indiclinguist** [NikolaiT/se-scraper#4]
Any fix for the following error?
.... 
at Object.scrape_google_pup (//se-scraper/se-scraper/src/modules/google.js:65:15) name: 'TimeoutError' }
Google detected the scraping. Aborting.
$

**Comment by hubitor** [comment]
Same here...
Also it seems that infospace blocked my IP for some time.

**Comment by NikolaiT** [comment]
Well this my friends is the reason why I made https://scrapeulous.com/

Scraping is inherently not liked by large search engines and thus they block you after some time.

You could use your own proxies or use any scraping service like mine above.

**Comment by NikolaiT** [comment]
By passing it to the scraping configuration:

	event = {
		// the user agent to scrape with
		user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36',
		// if random_user_agent is set to True, a random user agent is chosen
		random_user_agent: true,
		// use a proxy for all connections
		// example: 'socks5://78.94.172.42:1080'
		// example: 'http://118.174.233.10:48400'
		proxy: 'socks5://78.94.172.42:1080',
	};

**Comment by przemek-nowicki** [comment]
It doesn't work even when I set proxy. Is it me, or google change something ? 
The proxy works just fine for other browsers (ie. bing, duckduckgo).
