### ISSUE TITLE
STANDARD_TIMEOUT too low

### ISSUE THREAD

**Issue by raigorx** [NikolaiT/se-scraper#48]
`Problem with scraping twitter.com in search engine google: TimeoutError: waiting for selector "#fbar" failed: timeout 10000ms exceeded`

https://github.com/NikolaiT/se-scraper/blob/b513bb0f5bd4f4d4650a94d7a43e955a796fcc01/src/modules/se_scraper.js#L32

Solution extend timeout, this value should be a parameter
```
this.STANDARD_TIMEOUT = 5000000;
```

**Comment by NikolaiT** [comment]
No this should not be such a paramter. 10s is enough, if not, there is some problem with your connection or RAM.
