### ISSUE TITLE
Docker image not working at download and a build

### ISSUE THREAD

**Issue by QuentinAdt** [NikolaiT/se-scraper#50]
Hi, 

i can't get the docker image:
1/  dowloaded with the command specified in the README.md:
`docker pull tschachn/se-scraper
`
=> it misses a tag.
Since there is not image with the tag "latest", it doesn't work.

It works with:
`docker pull tschachn/se-scraper:firsttry
`

2/ built locally using Dockerfile
It ends with:
```
Step 10/17 : RUN npm install     && npm run build
 ---> Running in 04260d193eb5

> puppeteer@1.20.0 install /se-scraper/node_modules/puppeteer
> node install.js

Chromium downloaded to /se-scraper/node_modules/puppeteer/.local-chromium/linux-686378
added 274 packages from 642 contributors and audited 548 packages in 24.965s
found 0 vulnerabilities

npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-17T09_35_36_210Z-debug.log
```
Did I miss something ?
I build it with:
`sudo docker build -t se_scraper .
`

**Comment by NikolaiT** [comment]
Thanks for your comment. I fixed the tag issue and added created a new docker build. It should work now. Please follow the [install description here](https://github.com/NikolaiT/se-scraper#docker-support)
