### ISSUE TITLE
Browser Language

### ISSUE THREAD

**Issue by gregghawes** [NikolaiT/se-scraper#72]
Is there any way to set the browser language? I tried sending [--lang=de-DE, de] with chrome_flags but according to the evasion result it's still showing en-US, en

**Comment by HugoPoi** [comment]
I confirm, I use this option in production, it's working for me, but I also use some proxy in the target country. The tests do not cover this option yet but a PR is welcome to ensure the flag is working as intended.

**Comment by gregghawes** [comment]
> I confirm, I use this option in production, it's working for me, but I also use some proxy in the target country. The tests do not cover this option yet but a PR is welcome to ensure the flag is working as intended.

Thank you @HugoPoi. Do you have any recommendations on proxies?

**Comment by HugoPoi** [comment]
Not really, we use a very complex but cheap solution, consumer VPNs with our own proxy manager which handle the connection to the VPN and give a socks5 for se-scraper.

You have : Luminati, Infatica, smartproxy.com can do job I think.
