### ISSUE TITLE
trying to run docker, can't open docker-entrypoint

### ISSUE THREAD

**Issue by ryx2** [NikolaiT/se-scraper#75]
After pulling the docker image, when running 

sudo docker run -p 3000:3000 tschachn/se-scraper:latest

I see: 

/bin/sh: 0: Can't open /usr/local/bin/docker-entrypoint.sh

**Comment by HugoPoi** [comment]
Are you sure, because I try just your command and it run good for me. Maybe you have old image, I'm not sure docker pull every time with `latest`

**Comment by ryx2** [comment]
I just needed to install the latest docker.io

Thanks!
