### ISSUE TITLE
A bit more help for total noobs

### ISSUE THREAD

**Issue by sdspieg** [NikolaiT/se-scraper#9]
Thanks for sharing this I was able to follow the Quickstart instructions until it said "then create a file with the following contents and start scraping." So I installed node.Js And NPM on my Ubuntu Bionic, I created that environment variable with the export command, I installed se-scraper. I then went into nano to create a file with the content. But then what? Do we save it as a .sh file, make it executable and then run it (that's what I tried, but that doesn't work)? Or is there an intermediate step that is obvious for cognoscenti, but not for semi-geeks like many of us? :) I'd be grateful if you could put me on the right track (and save me many hours). Thanks!
Update - I suspect it has to be a js file. Looking for instructions on node.js... But so if you could add that to your readme file, that'd be great!

**Comment by NikolaiT** [comment]
The readme is now updated with better instructions. 

I hope it is accessible for everyone right now.
